#!/usr/bin/env python3
"""
local_mops_revenue.py — Playwright 爬 MOPS 月營收，逐支股票抓取
================================================================
使用方式:
  cd backend
  python local_mops_revenue.py                    # 全部股票寫入 DB
  python local_mops_revenue.py --output csv       # 存成 revenue.csv（不需連 DB）
  python local_mops_revenue.py --output sql       # 存成 revenue.sql（不需連 DB）
  python local_mops_revenue.py --limit 50         # 只跑前 50 支測試
  python local_mops_revenue.py --start 2330       # 從指定股票續跑

公司環境（port 5432 被封）：
  python local_mops_revenue.py --output csv --stock-list stocks.txt
  → 爬完存 CSV，再到 Supabase Dashboard → Table Editor → Import CSV
================================================================
"""
import argparse, asyncio, csv, os, sys, time
from datetime import datetime

def _load_dotenv():
    env_file = os.path.join(os.path.dirname(__file__), ".env")
    if not os.path.exists(env_file):
        return
    with open(env_file, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ[k.strip()] = v.strip().strip('"').strip("'")

_load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    print("[ERR] DATABASE_URL 未設定，請確認 .env 檔")
    sys.exit(1)

try:
    import psycopg2
except ImportError:
    print("[ERR] 缺少 psycopg2，請執行：pip install psycopg2-binary")
    sys.exit(1)


def _get_conn():
    return psycopg2.connect(DATABASE_URL)


def _get_stock_list_from_db():
    with _get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT code FROM product_universe ORDER BY code")
            return [{"code": r[0]} for r in cur.fetchall()]


def _get_stock_list_from_file(path: str):
    with open(path, encoding="utf-8") as f:
        codes = [line.strip() for line in f if line.strip()]
    return [{"code": c} for c in codes]


def _parse_revenue_table(text: str) -> dict:
    """Parse table inner_text (tab-separated) → revenue dict."""
    result = {}
    yoy_count = 0
    for line in text.splitlines():
        if "\t" not in line:
            continue
        parts = line.split("\t", 1)
        key = parts[0].strip()
        val = parts[1].replace(",", "").strip() if len(parts) > 1 else ""
        if not val:
            continue
        try:
            if "本月" in key:
                result["revenue"] = int(float(val))
            elif "增減百分比" in key:
                yoy_count += 1
                if yoy_count == 1:  # first 增減百分比 = MoM or YoY vs last year
                    result["revenue_yoy"] = float(val)
        except Exception:
            pass
    return result


def _save_to_db(rows: list) -> int:
    """Upsert rows into Supabase fundamentals. Returns error count."""
    sql = """
        INSERT INTO fundamentals
            (stock_id, pe_ratio, pb_ratio, dividend_yield, eps,
             revenue, revenue_mom, revenue_yoy, revenue_date, source, updated_at)
        VALUES (%s, NULL, NULL, NULL, NULL, %s, NULL, %s, %s, 'mops_playwright', NOW())
        ON CONFLICT (stock_id) DO UPDATE SET
            revenue      = EXCLUDED.revenue,
            revenue_yoy  = EXCLUDED.revenue_yoy,
            revenue_date = EXCLUDED.revenue_date,
            source       = EXCLUDED.source,
            updated_at   = NOW()
    """
    errors = 0
    try:
        with _get_conn() as conn:
            with conn.cursor() as cur:
                for code, data, revenue_date in rows:
                    try:
                        cur.execute(sql, (code, data.get("revenue"), data.get("revenue_yoy"), revenue_date))
                    except Exception:
                        errors += 1
            conn.commit()
    except Exception as e:
        print(f"  [WARN] DB 連線錯誤: {e}")
        errors += len(rows)
    return errors


def _save_to_csv(rows: list, path: str):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["stock_id", "revenue", "revenue_yoy", "revenue_date", "source", "updated_at"])
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        for code, data, revenue_date in rows:
            w.writerow([code, data.get("revenue"), data.get("revenue_yoy"), revenue_date, "mops_playwright", now_str])
    print(f"\n[FILE] CSV 已儲存：{path}（{len(rows)} 筆）")
    print("   → 到 Supabase Dashboard → Table Editor → fundamentals → Import CSV")


def _save_to_sql(rows: list, path: str):
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(path, "w", encoding="utf-8") as f:
        f.write("-- MOPS 月營收 INSERT — generated by local_mops_revenue.py\n")
        f.write(f"-- {now_str}  rows={len(rows)}\n\n")
        for code, data, revenue_date in rows:
            rev = data.get("revenue") or "NULL"
            yoy = data.get("revenue_yoy")
            yoy_s = str(yoy) if yoy is not None else "NULL"
            f.write(
                f"INSERT INTO fundamentals (stock_id, revenue, revenue_yoy, revenue_date, source, updated_at)\n"
                f"VALUES ('{code}', {rev}, {yoy_s}, '{revenue_date}', 'mops_playwright', NOW())\n"
                f"ON CONFLICT (stock_id) DO UPDATE SET\n"
                f"  revenue=EXCLUDED.revenue, revenue_yoy=EXCLUDED.revenue_yoy,\n"
                f"  revenue_date=EXCLUDED.revenue_date, source=EXCLUDED.source, updated_at=NOW();\n\n"
            )
    print(f"\n[FILE] SQL 已儲存：{path}（{len(rows)} 筆）")
    print("   → 到 Supabase Dashboard → SQL Editor → 貼上或上傳此檔執行")


async def scrape_all(codes: list, sleep_sec: float = 1.5, output: str = "db", out_file: str = ""):
    from playwright.async_api import async_playwright

    now = datetime.now()
    revenue_date = f"{now.year}-{now.month:02d}"
    rows = []
    written = skipped = errors = 0

    print(f"\n[月營收] 開始爬取 {len(codes)} 支股票，revenue_date={revenue_date}，輸出={output}")
    print(f"  {'#':<5} {'代號':<7} {'月營收':>15} {'YoY%':>8}  狀態")
    print("  " + "-" * 55)

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled"]
        )
        ctx = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
            locale="zh-TW",
            viewport={"width": 1280, "height": 900},
        )
        await ctx.add_init_script("Object.defineProperty(navigator,'webdriver',{get:()=>undefined})")
        page = await ctx.new_page()

        await page.goto("https://mops.twse.com.tw/mops/#/web/t05st10_ifrs",
                        timeout=30000, wait_until="networkidle")
        await page.wait_for_timeout(1500)

        for i, code in enumerate(codes, 1):
            try:
                modify_btn = page.locator("button:has-text('修改條件')")
                if await modify_btn.count() > 0 and await modify_btn.first.is_visible():
                    await modify_btn.first.click()
                    await page.wait_for_timeout(500)

                await page.fill("#companyId", "")
                await page.fill("#companyId", code)
                await page.wait_for_timeout(800)

                suggestion = page.locator(f"button:has-text('{code}')")
                if await suggestion.count() > 0:
                    await suggestion.first.click()
                    await page.wait_for_timeout(400)
                else:
                    skipped += 1
                    print(f"  {i:<5} {code:<7} {'':>15} {'':>8}  [SKIP] 找不到")
                    continue

                await page.click("button:has-text('查詢')")
                await page.wait_for_timeout(3000)

                table = await page.query_selector("table")
                if not table:
                    skipped += 1
                    print(f"  {i:<5} {code:<7} {'':>15} {'':>8}  [SKIP] 無資料")
                    continue

                text = await table.inner_text()
                data = _parse_revenue_table(text)

                if not data.get("revenue"):
                    skipped += 1
                    print(f"  {i:<5} {code:<7} {'':>15} {'':>8}  [SKIP] 解析失敗")
                    continue

                if output == "db":
                    db_err = _save_to_db([(code, data, revenue_date)])
                    if db_err:
                        errors += 1
                        status = "[ERR] DB錯誤"
                    else:
                        written += 1
                        status = "[OK]"
                else:
                    rows.append((code, data, revenue_date))
                    written += 1
                    status = "[OK]"
                print(f"  {i:<5} {code:<7} {data['revenue']:>15,} {data.get('revenue_yoy',0):>7.1f}%  {status}", flush=True)

                await asyncio.sleep(sleep_sec)

            except Exception as e:
                errors += 1
                print(f"  {i:<5} {code:<7} {'':>15} {'':>8}  [ERR] {str(e)[:40]}", flush=True)
                try:
                    await page.goto("https://mops.twse.com.tw/mops/#/web/t05st10_ifrs",
                                    timeout=20000, wait_until="networkidle")
                    await page.wait_for_timeout(1000)
                except Exception:
                    pass

        await browser.close()

    print(f"\n{'='*55}")
    print(f"  [OK] 寫入 {written} 筆  [SKIP] 略過 {skipped} 筆  [ERR] 錯誤 {errors} 筆")

    if output == "csv":
        _save_to_csv(rows, out_file or "revenue.csv")
    elif output == "sql":
        _save_to_sql(rows, out_file or "revenue.sql")

    print(f"{'='*55}\n")
    return written


def main():
    parser = argparse.ArgumentParser(description="MOPS 月營收 Playwright 爬蟲")
    parser.add_argument("--limit",      type=int,   default=0,    help="只跑前 N 支（測試用）")
    parser.add_argument("--start",      type=str,   default="",   help="從指定代號開始（斷點續傳）")
    parser.add_argument("--sleep",      type=float, default=1.5,  help="每支間隔秒數（預設 1.5）")
    parser.add_argument("--output",     type=str,   default="db", choices=["db", "csv", "sql"],
                        help="輸出模式：db（直接寫DB）、csv（存CSV）、sql（存SQL檔）")
    parser.add_argument("--out-file",   type=str,   default="",   help="輸出檔名（預設 revenue.csv / revenue.sql）")
    parser.add_argument("--stock-list", type=str,   default="",   help="股票代號清單 txt 檔（每行一個代號，不填則從DB取）")
    args = parser.parse_args()

    # Get stock list
    if args.stock_list:
        products = _get_stock_list_from_file(args.stock_list)
        print(f"[LIST] 從檔案載入 {len(products)} 支股票：{args.stock_list}")
    elif args.output == "db":
        products = _get_stock_list_from_db()
        if not products:
            print("[ERR] 無法取得股票清單")
            sys.exit(1)
    else:
        print("[ERR] --output csv/sql 需要指定 --stock-list <檔案>（或改用 --output db 從資料庫取）")
        print("   快速產生股票清單：python -c \"print('\\n'.join(['2330','2317','2454','2382']))\" > stocks.txt")
        sys.exit(1)

    codes = [p["code"] for p in products if p.get("code")]

    if args.start:
        try:
            idx = codes.index(args.start)
            codes = codes[idx:]
            print(f"從 {args.start} 開始，剩 {len(codes)} 支")
        except ValueError:
            print(f"找不到 {args.start}，從頭開始")

    if args.limit:
        codes = codes[:args.limit]

    print(f"\n{'='*55}")
    print(f"  [CHART] MOPS 月營收爬蟲（Playwright）")
    print(f"  股票數: {len(codes)}  間隔: {args.sleep}s  輸出: {args.output}")
    print(f"  預計時間: {len(codes) * (args.sleep + 3.5) / 60:.0f} 分鐘")
    print(f"{'='*55}")

    asyncio.run(scrape_all(codes, sleep_sec=args.sleep, output=args.output, out_file=args.out_file))


if __name__ == "__main__":
    main()
